export const INITIAL_VEHICLE_STATE = {
    codigo_patrimonial: '',
    clase_patrimonial: 'Terrestre',
    categoria_patrimonial: 'Pasajeros',
    secuencial: '',
    placa: '',
    marca: '',
    modelo: '',
    color: '',
    anio_fabricacion: new Date().getFullYear(),
    potencia_hp: '',
    numero_motor: '',
    numero_chasis: '',
    tipo_combustible: 'DIESEL',
    capacidad_carga_kg: '',
    capacidad_pasajeros: '',
    bateria_tipo: 'Plomo-Ácido',
    bateria_celdas: 6,
    bateria_voltios: 12,
    bateria_amperios: 70,
    numero_ejes: 2,
    configuracion_ejes: '4x2',
    estado_pintura: 'BUENO',
    estado_faros: 'BUENO',
    estado_lunas: 'BUENO',
    inventario_herramientas: 'Gato hidráulico, llave de ruedas, triángulo de seguridad, linterna.',
    valor_adquisicion: '',
    vida_util_anios: 10,
    seguro_anual: '',
    licenciamiento_anual: '',
    periodicidad_mantenimiento_km: 5000,
};